<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenBaseCamp.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenBaseCamp.Core.Tests" />
  </ItemGroup>

</Project>
